### ISSUE TITLE
Support TLS using Let's Encrypt certs

### ISSUE THREAD

**Issue by jbowens** [jbowens/request-catcher#1]
Serve requestcatcher and all its subdomains over https. It'll be a little tricky.

- [ ] Configure the net/http Server so that it's safe to expose requestcatcher directly instead of putting it behind nginx. ([relevant blog post](https://blog.cloudflare.com/exposing-go-on-the-internet/))
- [ ] Use the [golang.org/x/crypto/acme/autocert](https://godoc.org/golang.org/x/crypto/acme/autocert) package to automatically get certificates for new hosts.

**Comment by jbowens** [comment]
Not feasible without allowing someone to get requestcatcher.com rate-limited by Let's Encrypt. Real answer is still an expensive wildcard domain.

**Comment by agassi88** [comment]
Thank you for perfect and free tool!
