### ISSUE TITLE
Instructions to run locally

### ISSUE THREAD

**Issue by saifsmailbox98** [jbowens/request-catcher#16]
Would appreciate it if someone can add instructions to run it locally.

**Comment by tcables** [comment]
This. Why has this project NOT provided this? @jbowens

**Comment by jbowens** [comment]
It should be straightforward for anyone that knows how to run a Go application. I wrote this project about a decade ago, provide it for free and do not have time to provide detailed documentation or ergonomics. It’s provided as-is. Have fun
