### ISSUE TITLE
requestcatcher.com not working, 504 gateway timeout

### ISSUE THREAD

**Issue by agassi88** [jbowens/request-catcher#3]
![image](https://user-images.githubusercontent.com/11833589/32900954-521b5744-caf7-11e7-95e0-0930b6f4ea62.png)

**Comment by jbowens** [comment]
Thanks for reporting! Working on a fix now.

**Comment by jbowens** [comment]
Back up! Thanks again

**Comment by agassi88** [comment]
Thank you for perfect and free tool!
